const data = {
  products: [
    {
      _id:'1',
      name: 'Excavadora',
      slug: 'excavadora-amarilla',
      category: 'Maquinaria',
      image: '/images/e1.jpg',
      price: 2000000,
      countInStock: 5,
      brand: 'brand',
      rating: 1,
      numReviews: 10,
      description: 'Excavadora de color amarillo',
    },
    {
      _id:'2',
      name: 'Libros de historia',
      slug: 'libros-de-historia',
      category: 'Libros',
      image: '/images/l1.jpg',
      price: 30,
      countInStock: 5,
      brand: 'ghandi',
      rating: 2,
      numReviews: 10,
      description: 'libro de historia del banco de mexico',
    },
    {
      _id:'3',
      name: "adorno",
      slug: "adorno",
      category: "decoracion",
      image: "/images/d1.jpg",
      price: 30,
      countInStock: 0,
      brand: "madera",
      rating:4,
      numReviews: 10,
      description: "Lindo adorno de madera",
    },
    {
      _id:'4',
      name: "predio",
      slug: "predio",
      category: "terrenos",
      image: "/images/c1.jpg",
      price: 319000.00,
      countInStock: 1,
      brand: "n/a",
      rating: 5,
      numReviews: 10,
      description: "Lterreno en la coloni los jardines",
    },
  ],
};

export default data;
